language: php
sudo: false

php:
  - 5.6
  - 7.0

cache:
  directories:
    - "$HOME/.composer/cache"

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar config --global github-oauth.github.com $GH_TOKEN
  - php -d memory_limit=-1 composer.phar install --no-interaction

script:
  - php composer.phar test

notifications:
  slack:
    secure: nxawzmFAjjCg0HZq2I6RL100KttmRT19T0VI8+14Lk70O9A2Oh2T2CQ8ulgBJlr7wXeB9dllWIjlHIYShws0UWuLAMy1KJD20EVtbh9wt8J5BfL3EqrrZY4i7WXmIfRhl14Gi/9luqNFEBW9bMV7ldg1r2asMhjB8zY5QT6vqqD75XY1GgoRP8kBTId2zw+NbHu0r3zjn1sHN8eay5/zQLq71zyL5nPVte1TcHkh0rnGGdrJm8BusTBu1nubZYTTIyfrUbnJT1d5g1zjGt9VkOoAWR7bJeK/xMTDOTCFSd1qdH7fYWKg44t+zMoa2Zm5B7bf8hJuXGaT3QVG6/EWrh16h+TcJMUYOEsXmIaAwK2LSoBlBk2OD5NiqP/9LSJT3iBqn8p2Q6akRiy+4u/GVKWQrW/6v01a8BW0Gf/CylU3kRsEZZB7K2oXu2qWbBfJspsDGxFjUbK7NhlisPkC4AQXzaFeUtS7ZeLOgSKDs1kIkR5hA26vFsPrRu67e8eSsDZ83k3O+SAatPez8dqoVcxUyyzZhyUuRPL6A6P0as3O8ldPcaLIk3xm+Qxx33lcHQXgvX3H4YWcKa/GLHlYUzhuJ1lqNMYLffhXVNxRsB0TtyYWq4ja+psru+gMUHzmeVj6y81Uz8ipQ4lJnqe1yE0yZCocXcfY5Cwif71JGnE=
